### ISSUE TITLE
[FEATURE]: Create new Highlight component to highlight part of a string

### ISSUE THREAD

**Issue by herrardo** [empathyco/x#381]
### How can the project be improved?

Create a new Highlight component to be in charge of highlighting the part of a suggestions that matches the current query in the search box.

### How can this be solved?

The code is already written, but as part of other components.

### Proposed solution

Extract the highlight logic from the [BaseSuggestion](https://github.com/empathyco/x/blob/main/packages/x-components/src/components/suggestions/base-suggestion.vue) component into a new `<Highlight :value="stringToHighlight" highlight="highlight" />` component. The name of the prop is just a suggestion, you can look for a better name.

This component can then be used only in components that should support highlighting, like QuerySuggestion or HistoryQuery. But not by default in NextQuery or PopularSearch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by jtomasdias00** [comment]
Hey @herrardo we noticed that our delivery (that we mentioned on another issue #385 ) was based on two contributions. Can we (me and @BrunoRodrigues1999) take on this issue as well?

**Comment by jtomasdias00** [comment]
Also, where can we visually see this effect?

**Comment by 17h51a05d8** [comment]
NA
