### ISSUE TITLE
[FEATURE]: Avoid forbidden characters in the search box

### ISSUE THREAD

**Issue by herrardo** [empathyco/x#383]
### How can the project be improved?

Avoid forbidden characters in the search box in order to prevent security issues such as XSS through code injection 

### How can this be solved?

Given a shopper typing in the search-box component
when the shopper types forbidden characters like `<` or `>`
then the search box prevents the acceptance of this characters
and nothing changes in the search box.

### Proposed solution

Add a config to the SearchBox module to pass the characters to be forbidden.

### Additional information

[This is the location of the search-box module
](https://github.com/empathyco/x/tree/main/packages/x-components/src/x-modules/search-box)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by ritikBhandari** [comment]
Hi @herrardo,
Can I take up this issue?

**Comment by javieri-empathy** [comment]
Sure @ritikBhandari! Ping us if you need any help. You can start by taking a look at the [search-input](https://github.com/empathyco/x/blob/main/packages/x-components/src/x-modules/search-box/components/search-input.vue) component.

**Comment by ritikBhandari** [comment]
Sure. Thank you!

**Comment by ritikBhandari** [comment]
So what are the forbidden characters other than `<` and `>`? I guess majority the special characters right?

**Comment by tiborux** [comment]
@ritikBhandari `<` and `>`  should be enough.

**Comment by ritikBhandari** [comment]
Ohkay!
You've made it easier :)

**Comment by herrardo** [comment]
> Ohkay! You've made it easier :)

Hey @ritikBhandari !! Are you still interested or faced any problems? Let us know, have a good weekend ;)

**Comment by wannieman98** [comment]
Can I give this issue a try?

**Comment by herrardo** [comment]
> Can I give this issue a try?

Sure @wannieman98 👍

**Comment by ritikBhandari** [comment]
I'm really sorry @herrardo I was involved in some unavoidable issues lately. I'll definitely do it ASAP or @wannieman98 can also try.

**Comment by herrardo** [comment]
> I'm really sorry for the inconvinience @herrardo. I was involved in some unavoidable issues lately. I'll definitely do it ASAP or @wannieman98 can also try.

Don't worry about it. If you both try we'll review both PR's 🙌

**Comment by alonsogarciapablo** [comment]
Hola! @herrardo I've been taking a look at this today to get familiar with this codebase. I have a PR ready implementing this new prop as a blacklist, but I just bumped into the following article that discusses the disadvantages of using blacklists (vs using whitelists):

https://research.nccgroup.com/wp-content/uploads/2020/07/ncc-group-whitepaper_the-disadvantages-of-a-blacklist-based-approach-to-input-validation.pdf

Have you guys considered using a whitelist instead (we would need to define what's the acceptable input)? Thank you!

**Comment by herrardo** [comment]
@wannieman98 Thanks for the contribution! Your PR took a while to merge because we had issues to merge PR from outside the organization but everything got solved finally, thanks again ;)
