### ISSUE TITLE
[FEATURE]: As a user, I want results to show another image on hover

### ISSUE THREAD

**Issue by herrardo** [empathyco/x#452]
### How can the project be improved?

The [BaseResultImage](https://github.com/empathyco/x/blob/main/packages/x-components/src/components/result/base-result-image.vue) component is able to show an image, but is not ready to show another on hover.

We would like to provide the possibility to show another image on result image hover.

### How can this be solved?

Scenario
Given a shopper who is seeing a result
when the user hovers the result image
then the image is animated to show an alternative image
when the user stops hovering over the image
then the original image is shown

### Proposed solution

We can create a computed property `images` that is calculated with the Result images filtered to exclude the images present in `failedImages`.

Then we can modify `getImageSrc` in this way:

```
get imageSrc(): string {
      return !this.hasEnteredView ?
        ''
        : this.hover && this.images.length > 1
          ? this.images[1]
          : this.images[0];
    }
```

And activate hover property when the user hovers the image.

### Customizations supported

- Provide a way no enable&disable the hover behavior, maybe with a prop flipImageOnHover (or other name), for example
- Animation required
- Try to use composition

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by jatinmark** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by herrardo** [comment]
Hello @jatinmark, thanks for the offer!! We are trying to define better this task because we are struggling when deciding if we want to do this on the BaseResultImage component or use composition and do it in another. You can grab this and do a PR, but due to this decision,  you might take a path that is not ideal in the end. So you can take it if you want to have this on mind or take this [other issue](https://github.com/empathyco/x/issues/751), easier, to begin with.

**Comment by herrardo** [comment]
Closing this issue because we want to define it better to avoid contributors to work on an issue with poor requirements
