### ISSUE TITLE
[FIX]: Rename event to be a typed XEvent

### ISSUE THREAD

**Issue by herrardo** [empathyco/x#751]
### How can the project be improved?

Change name of Event that is not a X Event to use the proper one.

### How can this be solved?

In [empathize.vue](https://github.com/empathyco/x/blob/main/packages/x-components/src/x-modules/empathize/components/empathize.vue)

```
@Prop({
      default: () => [
        'UserClosedEmpathize',
        'UserSelectedASuggestion',
        'UserPressedEnter',
        'UserBlurredSearchBox'
      ]
    })
    protected eventsToCloseEmpathize!: XEvent[];
```

we need to change UserPressedEnter to UserPressedEnterKey and type the prop default value properly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by jatinmark** [comment]
I can work on this issue

**Comment by herrardo** [comment]
Assigned @jatinmark , sorry for the delay

**Comment by jatinmark** [comment]
@herrardo i fixed the issue can you check the PR.
