### ISSUE TITLE
[FEATURE]: As a shop manager, I'd like to promote my products using product labels

### ISSUE THREAD

**Issue by fernandossmm** [empathyco/x#776]
### How can the project be improved?

Motive currently processes their "Out of stock" label with logic on the front-end side, and uses just a `<span>` element.

To offer more possibilities of label customization in the future, we'd like to change it so that backend indexes products with their respective labels, and frontend receives those labels and chooses how to display them given their information. This allows us to display labels for information the search layer doesn't receive, like the actual stock amount (we just get 0 or 1) or the shop's custom attributes.

### How can this be solved?

Inside of the `product` object received in the search response, we'll get something like this (key names not final):
```
"product_labels":[
   {
   		"id":"out_of_stock",
   		"text":"Out of stock until december"
   },
   {
   		"id":"on_sale",
   		"text":"Sale!!!"
   },
]
```

Front will then show the first of the given labels in the top-right corner, styled by CSS (for now).

### Proposed solution

We believe a new Component can be added that receives all customization information (described below) and changes its style to match.

This new label Component's position inside the Product Card will be the responsibility of ___.

### Customizations supported

_These are all possible future improvements and customizations, that we may or may not get to do._

We'd like to add to the label information, to inform the display of it in the frontend:
- Label font color
- Label background color
- Label position: Top-right, Top-left, Bottom-right, Bottom-left, Bottom

A label showing the sale % is also wanted, where the user can input text and some of it will be replaced by the item sale percentage. For example, `Now {discount_percent}% off!` would become "Now 50% off!". This could also extend to `Now {discount_amount}€ off!` would become "Now 2.50€ off!"

Also seen in other shops, some labels may have a tooltip on hover. In Motive there are no plans to implement this.

### Additional information

[Figma](https://www.figma.com/file/XqE8Z9jNwL0nspxbQxyzEM/Design-tasks?node-id=5369%3A266262
) (may not be reachable without an Empathy.co account).

[Current implementation](https://coallagourmet.com/es/?mot_q=queso).

[Feature requests received by Motive customers](https://searchbroker.atlassian.net/browse/MFR-149) (may not be reachable without an Empathy.co account).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by herrardo** [comment]
Good afternoon @fernandossmm 

We have reviewed the feature request and we think the component wouldn't have much responsibility or logic, at the end of the day, the component will show some info that is provided by the search response, but it wouldn't do much about it.

This response:

```
Label font color
Label background color
Label position: Top-right, Top-left, Bottom-right, Bottom-left, Bottom
```

would be Motive specific, so we can't force Empathy or other companies' endpoints to include that in the search response as they depend on the feed, the fields that provide that info can be very different and we would be forcing the response in a not organic way, resulting in extra workload for endpoints and not much advantage for Frontend purposes as the logic of the component is quite small.



To accomplish this:

_A label showing the sale % is also wanted, where the user can input text and some of it will be replaced by the item sale percentage. For example, Now {discount_percent}% off! would become "Now 50% off!". This could also extend to Now {discount_amount}€ off! would become "Now 2.50€ off!"_

you could use the[ i18n component](https://kazupon.github.io/vue-i18n/guide/number.html#custom-formatting)


Finally, the thing that we think could be useful to standarize is to add a new `discount` property to the [ResultPrice](https://github.com/empathyco/x/blob/main/packages/search-types/src/result/result-price.model.ts) model, so we could turn this feature request into standarizing discount if you feel so.

**Comment by herrardo** [comment]
@fernandossmm have you commented this issue with your team, any thought about it?

**Comment by fernandossmm** [comment]
Hello @herrardo! We did take a look a the response, thanks! It's okay by us to make it Motive specific, it makes sense given that it's tied to our response. For now, the component isn't going to be customizable in the Playboard, so currently there's no need for custom logic, just the default CSS.

The discount % label is going to be calculated by our connector, so frontend would just display the text. Texts will not be customizable for now.

Regarding the proposed `discount` property, that may be appropriate as another issue, but I don't think it would be that useful, as you're duplicating information that can be extracted from the `value` and `originalValue` fields.

I think we can close this issue.
